version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: e64-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin11
      MYSQL_DATABASE: dgs
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/sql-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  nodejs:
    build: ./backend  # Make sure this directory contains a Dockerfile
    container_name: e64-api
    ports:
      - "3000:3000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - mynetwork
  frontend:
    build: ./frontend  # Make sure this directory contains a Dockerfile
    container_name: e64-frontend
    ports:
      - "3001:3000"  # Expose the React app on port 3001 on the host
      
networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
    driver: local
